<?php use hydrogen\config\Config; ?>
<!--[PAGETITLE]>Terms and Conditions<[/PAGETITLE]-->
<div id="page_terms" class="staticpage">
	<h1 id="pagetitle">Terms and Conditions for <?php echo Config::getVal('general', 'site_name'); ?> Usage</h1>
	<h2 class="pheading">Privacy</h2>
	<p>By using this site, you agree that <?php echo Config::getVal('general', 'site_name'); ?> is not responsible for the privacy of your information.  <?php echo Config::getVal('general', 'site_name'); ?>'s goal is not to share any personal information, but cannot be held liable if any information communicated to <?php echo Config::getVal('general', 'site_name'); ?> at any time is leaked, stolen, or made available to the public or third parties in any way.</p>
	<p>Any communication with <?php echo Config::getVal('general', 'site_name'); ?>, its affiliated sites, or anyone associated with <?php echo Config::getVal('general', 'site_name'); ?> ("affiliates") can be made public at any time, even if this communication does not take place on the website or in any official capacity.  This includes E-mails dealing with legal topics, and any communication that may contain a disclaimer that it's not to be shared. <?php echo Config::getVal('general', 'site_name'); ?> and all affiliates reserve the right to be open with any communication, information, or resource provided to them regardless of content.</p>
	<h2 class="pheading">Usage</h2>
	<p><?php echo Config::getVal('general', 'site_name'); ?> and affiliates are not responsible for user-submitted content or the actions of its users, regardless of whether the actions are legal or illegal.  The content submitted by <?php echo Config::getVal('general', 'site_name'); ?> users is the sole responsibility of the user who submitted it.</p>
	<p><?php echo Config::getVal('general', 'site_name'); ?> and affiliates are also not responsible for any damage to any electronic devices including computers, iPods, iPhones, or any other device that occurs due to or related to usage of this site.  All usage of any web application under the <?php echo Config::getVal('general', 'site_name'); ?> domain is at the user's own risk.</p>
	<h2 class="pheading">Abuse</h2>
	<p>By using this site, you agree to use only the parts of the site and server available to you from the <?php echo Config::getVal('general', 'site_name'); ?> web page.  Any attempt to harm <?php echo Config::getVal('general', 'site_name'); ?> or another site, resource, person, or property by using <?php echo Config::getVal('general', 'site_name'); ?> is forbidden and may be subject to prosecution.</p>
	<p>Submitting false or engineered information to <?php echo Config::getVal('general', 'site_name'); ?>, especially in the intent of harming the site, the quality of its content, or its users, will result in being banned from <?php echo Config::getVal('general', 'site_name'); ?>.  Furthermore, by attempting any kind of abuse toward <?php echo Config::getVal('general', 'site_name'); ?>, <?php echo Config::getVal('general', 'site_name'); ?> and its affiliates reserve the right to protect themselves using any method they chose, which may include proactive measures. <?php echo Config::getVal('general', 'site_name'); ?> and its affiliates are not responsible for any damage, harm, or otherwise negative result that comes to an abusive user or their equipment as a result of an attack on <?php echo Config::getVal('general', 'site_name'); ?>.</p>
	<h2 class="pheading">Rights</h2>
	<p><?php echo Config::getVal('general', 'site_name'); ?> and its affiliates reserve the right to deny access to the site, delete content, change content, or otherwise alter the user experience as they see fit. <?php echo Config::getVal('general', 'site_name'); ?> and its affiliates are not entitled to provide a service, and reserves the right to change the site, which may or may not include its user-submitted content, without reason or cause.</p>
</div>